services:
    # batch operations registry
    sygefor_core.batch_registry:
        class:  Sygefor\Bundle\CoreBundle\BatchOperations\BatchOperationRegistry

    # Override opentbs to fix meth_Merge_SectionNormal function
    opentbs:
        class:        Sygefor\Bundle\CoreBundle\Utils\HumanReadable\CustomOpenTBS
        arguments:    []

    # property accessor factory
    sygefor_core.human_readable_property_accessor_factory:
        class: Sygefor\Bundle\CoreBundle\Utils\HumanReadable\HumanReadablePropertyAccessorFactory
        arguments:
            - "@doctrine.orm.entity_manager"

    # batch operations decorators
    sygefor_core.batch.convert_type:
        class: Sygefor\Bundle\CoreBundle\BatchOperations\Training\ConvertTypeBatchOperation
        abstract: true
        arguments:
            - "@security.context"
            - "@sygefor_core.registry.training_type"
            - "@sygefor_training.semestered.search"
            - "@fos_elastica.client"
            - "@fos_elastica.index"
            - "@fos_elastica.index.sygefor3.semestered_training"

    # batch operations decorators
    sygefor_core.batch.csv:
        class: Sygefor\Bundle\CoreBundle\BatchOperations\Generic\CSVBatchOperation
        abstract: true
        arguments:
            - "@security.context"

    sygefor_core.batch.publipost:
        class: Sygefor\Bundle\CoreBundle\BatchOperations\Generic\MailingBatchOperation
        abstract: true
        arguments:
            - "@security.context"
        calls:
            - [ setContainer, [ "@service_container" ] ]

    sygefor_core.batch.pdf:
        class: Sygefor\Bundle\CoreBundle\BatchOperations\Generic\PDFBatchOperation
        abstract: true
        arguments:
            - "@knp_snappy.pdf"
            - "@templating"
            - "@security.context"
            - "@kernel"

    sygefor_core.batch.email:
          class: Sygefor\Bundle\CoreBundle\BatchOperations\Generic\EmailingBatchOperation
          calls:
              - [ setContainer, [ "@service_container" ] ]
          tags:
              - {name: sygefor_core.batch_operation_provider}

    sygefor_core.batch.session_registration_change:
          class: Sygefor\Bundle\CoreBundle\BatchOperations\Session\SessionRegistrationChangeBatchOperation
          calls:
              - [ setContainer, [ "@service_container" ] ]
          tags:
              - {name: sygefor_core.batch_operation_provider}

    sygefor_core.batch.inscription_status_change:
        class: Sygefor\Bundle\CoreBundle\BatchOperations\Inscription\InscriptionStatusChangeBatchOperation
        calls:
            - [ setContainer, [ "@service_container" ] ]
        tags:
            - {name: sygefor_core.batch_operation_provider}
