services:
    sygefor_core.serializer.inscription.event_subscriber:
        class: Sygefor\Bundle\CoreBundle\EventListener\ORM\InscriptionEventSubscriber
        tags:
            - { name: jms_serializer.event_subscriber }

    sygefor_core.password_encode.event_subscriber:
        class: Sygefor\Bundle\CoreBundle\EventListener\PasswordEncoderSubscriber
        arguments:
            - "@security.encoder_factory"
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    sygefor_core.inscription.orm.listener:
        class: Sygefor\Bundle\CoreBundle\EventListener\ORM\InscriptionListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    sygefor_core.organization_changed.orm.listener:
        class: Sygefor\Bundle\CoreBundle\EventListener\ORM\OrganizationChangedListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    sygefor_core.semestered_training_listener:
        class: Sygefor\Bundle\CoreBundle\EventListener\ORM\SemesteredTrainingListener
        arguments:
            - "@fos_elastica.object_persister.sygefor3.semestered_training"
            - "@fos_elastica.indexable"
            - "@fos_elastica.index.sygefor3.semestered_training"
        tags:
            - { name: doctrine.event_subscriber, connection: default  }
            - { name: fos_elastica.listener }

    sygefor_core.training.listener:
        class: Sygefor\Bundle\CoreBundle\EventListener\ORM\TrainingListener
        arguments:
            - "@sygefor_core.registry.training_type"
        tags:
            - { name: doctrine.event_subscriber, connection: default }


    sygefor_core.session.listener:
        class: Sygefor\Bundle\CoreBundle\EventListener\ORM\SessionListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
