parameters:
    jms_serializer.cache_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
    sygefor_core.vocabulary_registry.class: Sygefor\Bundle\CoreBundle\Utils\VocabularyRegistry

services:
    # Menu
    sygefor_core.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: sygefor_core.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    sygefor_core.menu_builder:
        class: Sygefor\Bundle\CoreBundle\Utils\MenuBuilder
        arguments: ["@knp_menu.factory"]
        calls:
            - [ setContainer, [ @service_container ] ]

    sygefor_core.configure_menu_listener:
        class: Sygefor\Bundle\CoreBundle\EventListener\ConfigureMenuListener
        arguments:
            - "@security.context"
            - "@router"
            - "@sygefor_core.registry.training_type"
        tags:
            - { name: kernel.event_listener, event: sygefor_core.menu_configure, method: onMenuConfigure }

    # training types registry
    sygefor_core.registry.training_type:
        class: Sygefor\Bundle\CoreBundle\Utils\TrainingTypeRegistry
        arguments: [null]

    # Serialization
    sygefor_core.serializer.handler.form_view:
        class: Sygefor\Bundle\CoreBundle\EventListener\Handler\FormViewHandler
        tags:
            - { name: jms_serializer.subscribing_handler }

    sygefor_core.serializer.handler.form_errors:
        class: Sygefor\Bundle\CoreBundle\EventListener\Handler\FormErrorIteratorHandler
        tags:
            - { name: jms_serializer.subscribing_handler }

    sygefor_core.serializer.access_rights.event_subscriber:
        class: Sygefor\Bundle\CoreBundle\EventListener\AccessRightsEventSubscriber
        arguments:
            - "@security.context"
        tags:
            - { name: jms_serializer.event_subscriber }

    # Listener
    sygefor_core.tree_trait_listener:
        class: Sygefor\Bundle\CoreBundle\EventListener\TreeTraitListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
