services:
    # AccessRightRegistry
    sygefor_core.access_right_registry:
        class: Sygefor\Bundle\CoreBundle\Security\Authorization\AccessRight\AccessRightRegistry
        arguments:
          - "@service_container"

    # AccessRightVoter
    sygefor_core.access_right_voter:
        class: Sygefor\Bundle\CoreBundle\Security\Authorization\Voter\AccessRightVoter
        public: false
        arguments:
            - "@sygefor_core.access_right_registry"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name:security.voter }

    # AdminVoter
    sygefor_core.admin_voter:
        class: Sygefor\Bundle\CoreBundle\Security\Authorization\Voter\AdminVoter
        public: false
        tags:
            - { name:security.voter }
