Sygefor\Bundle\CoreBundle\Entity\User:
    exclusion_policy: NONE
    properties:
        password:
            exclude: true
        salt:
            exclude: true
        # accessRights:
        #     exclude: true
        # organization:
        #     exclude: true