Sygefor\Bundle\CoreBundle\Entity\AbstractOrganization:
    properties:
      id:
        groups: [Default, api]
      name:
        groups: [Default, api]
      code:
        groups: [Default, api]
      users:
        exclude: true
      traineeRegistrable:
        groups: [api]
