services:
    sygefor_core.elastica_mapping_provider:
        class: Sygefor\Bundle\CoreBundle\MappingProvider\MappingProvider
        arguments:
            - '' #argument is set during configuration
            - '@service_container'
        #calls:
        #    - [setEntityManager, [@doctrine.orm.entity_manager]]

    sygefor_core.cascade_update_listener:
        class: Sygefor\Bundle\CoreBundle\Listener\ElasticaCascadeUpdateListener
        arguments:
            - "@kernel"
            - "@sygefor_core.elastica_mapping_provider"
        tags:
            - { name: doctrine.event_subscriber, priority: -2 }
            - { name: fos_elastica.listener }


    sygefor_email.search:
        class: Sygefor\Bundle\CoreBundle\Search\SearchService
        arguments: ["@fos_elastica.index.sygefor3.email"]