parameters:
    jms_serializer.cache_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
    sygefor_core.vocabulary_registry.class: Sygefor\Bundle\CoreBundle\Vocabulary\VocabularyRegistry

services:
    sygefor_core.menu_builder:
        class: Sygefor\Bundle\CoreBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        calls:
            - [ setContainer, [ @service_container ] ]

    sygefor_core.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: sygefor_core.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    sygefor_core.search:
        class: Sygefor\Bundle\CoreBundle\Search\SearchService
        arguments: ["@fos_elastica.index"]

    sygefor.search:
        alias: sygefor_core.search

    sygefor_core.serializer.handler.form_view:
        class: Sygefor\Bundle\CoreBundle\Serializer\Handler\FormViewHandler
        tags:
            - { name: jms_serializer.subscribing_handler }

    sygefor_core.serializer.handler.form_errors:
        class: Sygefor\Bundle\CoreBundle\Serializer\Handler\FormErrorIteratorHandler
        tags:
            - { name: jms_serializer.subscribing_handler }

    #listener
    sygefor_core.organization_changed.orm.listener:
        class: Sygefor\Bundle\CoreBundle\Listener\OrganizationChangedListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    sygefor_core.tree_trait_listener:
        class: Sygefor\Bundle\CoreBundle\Listener\TreeTraitListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    # taxonomy
    sygefor_core.vocabulary_registry:
        class: "%sygefor_core.vocabulary_registry.class%"

    # menu
    sygefor_core.configure_menu_listener:
        class: Sygefor\Bundle\CoreBundle\EventListener\ConfigureMenuListener
        arguments:
            - "@security.context"
        tags:
            - { name: kernel.event_listener, event: sygefor_core.menu_configure, method: onMenuConfigure }

    #serialization
    sygefor_core.serializer.access_rights.event_subscriber:
        class: Sygefor\Bundle\CoreBundle\Serializer\EventSubscriber\AccessRightsEventSubscriber
        arguments:
            - "@security.context"
        tags:
            - { name: jms_serializer.event_subscriber }