services:
    # AccessRightRegistry
    sygefor_core.access_right_registry:
        class: Sygefor\Bundle\CoreBundle\AccessRight\AccessRightRegistry
        arguments:
          - "@service_container"

    # AccessRightVoter
    sygefor_core.access_right_voter:
        class: Sygefor\Bundle\CoreBundle\Security\Authorization\Voter\AccessRightVoter
        public: false
        arguments:
            - "@sygefor_core.access_right_registry"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name:security.voter }

    # AdminVoter
    sygefor_core.admin_voter:
        class: Sygefor\Bundle\CoreBundle\Security\Authorization\Voter\AdminVoter
        public: false
        tags:
            - { name:security.voter }

    # vocabulary voters
    sygefor_core.rights.vocabulary.own:
        class:        Sygefor\Bundle\CoreBundle\Security\Authorization\AccessRight\Vocabulary\OwnOrganizationVocabularyAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Vocabulaires" }
    sygefor_core.rights.vocabulary.all:
        class:        Sygefor\Bundle\CoreBundle\Security\Authorization\AccessRight\Vocabulary\AllOrganizationVocabularyAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Vocabulaires" }
    sygefor_core.rights.vocabulary.national:
        class:        Sygefor\Bundle\CoreBundle\Security\Authorization\AccessRight\Vocabulary\NationalVocabularyAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Vocabulaires" }

    # user voters
    sygefor_core.rights.user.own:
        class:        Sygefor\Bundle\CoreBundle\Security\Authorization\AccessRight\User\OwnOrganizationUserAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Utilisateurs" }
    sygefor_core.rights.user.all:
        class:        Sygefor\Bundle\CoreBundle\Security\Authorization\AccessRight\User\AllOrganizationUserAccessRight
        tags:
            - { name: sygefor_core.right_provider, group: "Utilisateurs" }